### ISSUE TITLE
Numeric inputs other than age aren't validated before uploading

### ISSUE THREAD

**Issue by eshom** [discoRd-org/discoRd-survey#11]
If the age question isn't in the expected range, the user cannot submit their answer. However, for other dynamically added questions with numeric input this isn't true. The dynamically specified input range isn't respected.

We need to add some way so new questions with numeric input are validated to be in their defined possible range. If they aren't, the user shouldn't be able to submit their answers.

**Comment by acylam** [comment]
Good catch
