### ISSUE TITLE
Improve CSS

### ISSUE THREAD

**Issue by eshom** [discoRd-org/discoRd-survey#4]
The default theme is not great.

Other than that at least the following is required:
1) Center the questions.
2) More spacing between questions.

If you have any more theme ideas feel free to reply.

**Comment by iamericfletcher** [comment]
Pushed an update to the `I4` branch. @eshom @acylam care to take a look locally and let me know what you think? Note I added the server image and did some layout changes to the post submission page as well. It's a start!

**Comment by eshom** [comment]
Well it's centered, but now the choices aren't aligned. The image after submission is great.

**Comment by acylam** [comment]
I would also recommend referencing the CSS from a separate file using `tag$link` over inline CSS for clarity. https://shiny.rstudio.com/articles/css.html

**Comment by iamericfletcher** [comment]
Good idea, I am going to inline the changes till I have it right then move it to the separate file.  I made a slight update that aligns the choices. 

![image](https://user-images.githubusercontent.com/64165327/112893138-43b87680-90a8-11eb-8e56-a4e8c52f2763.png)

**Comment by iamericfletcher** [comment]
Also, what are our thoughts on changing what we can to drop-downs such as `What is your gender` and `Highest academic degree?`?

**Comment by acylam** [comment]
I'm fine with either (drop downs are great when there are many options), but a new input type will have to be added to the `generate_questions.R` code.
